const express = require("express")
const router = express.Router()
const {verifyAccessToken, isAdmin} = require("../middlewares/verifyToken")
const {EmployeeController} = require("../controllers/index")
const uploader = require("../config/cloudinary.config")
router.post("/", [verifyAccessToken, isAdmin], uploader.array("images"),EmployeeController.createEmployee)
router.get("/", [verifyAccessToken], EmployeeController.getListEmployee)
router.put("/is-display/:pid", [verifyAccessToken, isAdmin], EmployeeController.changeIsDisplayEmployee)
router.post("/filter-by-name", [verifyAccessToken], EmployeeController.findEmployeeByName)
router.put("/update", [verifyAccessToken, isAdmin], EmployeeController.updateEmployee)
router.get("/last-id-number", [verifyAccessToken, isAdmin], EmployeeController.lastIdNumber)
module.exports = router