const OrderController = require("../controllers/OrderController")

const express = require("express")
const router = express.Router()
const { verifyAccessToken, isAdmin } = require("../middlewares/verifyToken");
router.post("/", [verifyAccessToken], OrderController.createOrder)
router.get("/", [verifyAccessToken], OrderController.getAllOrder)
router.post("/filter-by-emloyee-name", [verifyAccessToken, isAdmin], OrderController.filterOrderByEmployee)
router.post("/filter-by-date", [verifyAccessToken, isAdmin], OrderController.filterOrderByDate)
router.post("/filter-by-condition", [verifyAccessToken], OrderController.filterOrders)
router.get("/sum", [verifyAccessToken, isAdmin], OrderController.sumTotalAmount)
router.post("/income-year", [verifyAccessToken], OrderController.getTotalAmountAndVATByYear)
router.post("/income-month", [verifyAccessToken], OrderController.getTotalAmountAndVATByMonth)
router.post("/extra-infor", [verifyAccessToken], OrderController.extraInfor)
router.post("/top-5-year", [verifyAccessToken, isAdmin], OrderController.top5ProductYear)
router.post("/top-5-month", [verifyAccessToken, isAdmin], OrderController.top5ProductMonth)
router.post("/revenue-month", [verifyAccessToken, isAdmin], OrderController.getTotalAmountAndVATByMonthReport)
router.post("/revenue-year", [verifyAccessToken, isAdmin], OrderController.getTotalAmountAndVATByYearReport)
router.post("/top-5-category-year", [verifyAccessToken, isAdmin], OrderController.top5ProductCategoryYear)
router.post("/top-5-category-month", [verifyAccessToken, isAdmin], OrderController.top5ProductCategoryMonth)
router.get("/top-7-last-days", [verifyAccessToken, isAdmin], OrderController.top5ProductLast7Days)
router.get("/top-30-last-days", [verifyAccessToken, isAdmin], OrderController.top5ProductLast30Days)
router.get("/top-365-last-days", [verifyAccessToken, isAdmin], OrderController.top5ProductLast365Days)
router.get("/top-category-7-last-days", [verifyAccessToken, isAdmin], OrderController.top5ProductCategoryLast7Days)
router.get("/top-category-30-last-days", [verifyAccessToken, isAdmin], OrderController.top5ProductCategoryLast30Days)
router.get("/top-category-365-last-days", [verifyAccessToken, isAdmin], OrderController.top5ProductCategoryLast365Days)
router.get("/revenue-current-day", [verifyAccessToken], OrderController.getTotalAmountCurrentDay)
router.get("/compare", [verifyAccessToken], OrderController.getTotalAmountComparison)
router.post("/order-day", [verifyAccessToken], OrderController.getOrderDay)
module.exports = router