const express = require("express");
const router = express.Router();
const { UserController } = require("../controllers/index");
const { verifyAccessToken, isAdmin } = require("../middlewares/verifyToken");
router.post("/register", UserController.register);
router.post("/login", UserController.login);
router.get("/current", verifyAccessToken, UserController.getCurrent);
router.post("/refresh-token", UserController.refreshAccessToken);
router.get("/logout", UserController.logout);
router.post("/forgotpassword", UserController.forgotPassword);
router.put("/resetpassword", UserController.resetPassword);
router.get("/", [verifyAccessToken, isAdmin], UserController.getUsers);
router.delete("/", [verifyAccessToken, isAdmin], UserController.deleteUser);
router.put("/current", verifyAccessToken, UserController.updateUser);
router.put("/:uid", [verifyAccessToken, isAdmin], UserController.updateUser);
module.exports = router;
